# Generated by Django 2.1.2 on 2018-10-26 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loanservices', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='loan',
            managers=[
            ],
        ),
    ]
