# Generated by Django 2.1.2 on 2018-10-26 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loanservices', '0002_auto_20181026_1537'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transact',
            name='loan_acc_no',
        ),
        migrations.AddField(
            model_name='transact',
            name='loan',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tranctions', to='loanservices.Loan'),
            preserve_default=False,
        ),
    ]
